### ISSUE TITLE
Compile Error - LocalFileIO

### ISSUE THREAD

**Issue by ratchet3789** [aws/lumberyard#553]
**Describe the bug**
Project fails to compile even with the #549 fix, gives the error 
`e\Amazon\Lumberyard\1.28.0.0\dev\Code\Framework\AzFramework\AzFramework\IO\LocalFileIO.cpp(502): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'AZStd::pair<const char *,const char *>'`

`e:\Amazon\Lumberyard\1.28.0.0\dev\Code\Framework\AzFramework\AzFramework\IO\LocalFileIO.cpp(502): note: No constructor could take the source type, or constructor overload resolution was ambiguous`
using Visual Studio 2019 16.10.0

**Steps to reproduce**
Modify the Qt files using #549 fix and then build using the Project Configurator and Visual Studio 2019 16.10.0

**Expected behavior**
Project builds successfully

**Screenshots/Logs**
https://pastebin.com/xfp6N1Aq

**Lumberyard version**
1.28.0.0

**Comment by WhyAreLess** [comment]
Same problem here

**Comment by AMZN-Gene** [comment]
Thanks for reporting! We'll be looking into this critical issue.

**Comment by ratchet3789** [comment]
Awesome thank you.
Given we're on Community Microsoft have made it a bit difficult.
For anyone else looking
https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release

**Comment by hendradarwin** [comment]
I also face same issue.
I'm using VS 2019 version 16.10.3,
and I found the workaround.

on the file `\dev\Code\Framework\AzFramework\AzFramework\IO\LocalFileIO.cpp` line 502
change from
```
m_aliases.push_back(AZStd::pair<const char*, const char*>(key, fullPath));
```
into
```
m_aliases.push_back(AZStd::pair<OSString, OSString>(key, fullPath));
```

The error will be gone and you should be able to compile `AzFramework` project.

**Comment by AvailableJosh** [comment]
> I also face same issue. I'm using VS 2019 version 16.10.3, and I found the workaround.
> 
> on the file `\dev\Code\Framework\AzFramework\AzFramework\IO\LocalFileIO.cpp` line 502 change from
> 
> ```
> m_aliases.push_back(AZStd::pair<const char*, const char*>(key, fullPath));
> ```
> 
> into
> 
> ```
> m_aliases.push_back(AZStd::pair<OSString, OSString>(key, fullPath));
> ```
> 
> The error will be gone and you should be able to compile `AzFramework` project.

I can confirm this workaround works, it worked for me! I spent countless hours trying to figure out the legitimate cause for this error, thank you so much!
